apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/karthik_jk/dc-metro-map@sha256:1a87a7483f8891a48da844d93a516de2d21d8c26587d85dd2ae5f55efe1cc7b8
        name: container-image
        resources: {}
status: {}
