apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map
    app.kubernetes.io/part-of: test-application
  name: dc-metro-map
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dc-metro-map
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dc-metro-map
    spec:
      containers:
      - image: quay.io/karthik_jk/dc-metro-map@sha256:1a87a7483f8891a48da844d93a516de2d21d8c26587d85dd2ae5f55efe1cc7b8
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
