apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map
    app.kubernetes.io/part-of: test-application
  name: dc-metro-map
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dc-metro-map
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dc-metro-map
    spec:
      containers:
      - image: quay.io/karthik_jk/dc-metro-map@sha256:c662ddf01f946d0afeeb0061e9771f6f95b3ac50643d5156b1ca7acaa83f2187
        imagePullPolicy: Always
        name: container-image
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
