apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: frontend-app-lmf6
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:856cf29e9ddab14fc156c4d198cd941afbd9c4554d2469c32e3b94f0d1b09d38
        name: my-nodejs
        resources: {}
status: {}
