apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: frontend-app-lmf6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frontend-app-lmf6
    app.kubernetes.io/part-of: test-application
  name: frontend-app-lmf6
  namespace: karthik-jk-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: frontend-app-lmf6
status:
  loadBalancer: {}
