apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-app-4jjx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-app-4jjx
    app.kubernetes.io/part-of: test-application
  name: test-app-4jjx
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: test-app-4jjx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: test-app-4jjx
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload:tPOTZ-test-app-4jjx
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
