apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: frontend-app-jpqa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frontend-app-jpqa
    app.kubernetes.io/part-of: test-application
  name: frontend-app-jpqa
  namespace: karthik-jk-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: frontend-app-jpqa
    weight: 100
status: {}
